server:
  port: 7000

spring:
  application:
    name: microservices-eureka

eureka:
  instance:
    hostname: microservices-eureka
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka # Port changed in eureka, need change default service url
      register-with-eureka: false # this is the eureka server, so not register itself
      fetch-registry: false # this is the eureka server, it does not need to find any service from eureka